_BASE_: "MESH-RCNN-FPN.yaml"
MODEL:
  #WEIGHTS: "../../meshrcnn/modeling/roi_heads/output/model_final.pth" 
  #WEIGHTS: "meshrcnn://coco_init_0719.pth"
  MASK_ON: True
  VOXEL_ON: True
  MESH_ON: True
  ZPRED_ON: True
  VIS_MINIBATCH: True
  RESNETS:
    DEPTH: 50
  RPN:
    IOU_THRESHOLDS: [0.2, 0.5, 0.7]
    IOU_LABELS: [-1, 0, -1, 1]
    SMOOTH_L1_BETA: 0.111
  ROI_HEADS:
    NAME: "MeshRCNNROIHeads"
    #BATCH_SIZE_PER_IMAGE: 4    
    BATCH_SIZE_PER_IMAGE: 4
    NUM_CLASSES: 1 
    IOU_THRESHOLDS: [0.2, 0.5]
    IOU_LABELS: [-1, 0, 1]
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 1.0    
  ROI_Z_HEAD:
    NAME: "FastRCNNFCHead"
    Z_REG_WEIGHT: 1.0
    SMOOTH_L1_BETA: 1.0
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    NUM_CONV: 4
  ROI_VOXEL_HEAD:
    NAME: "VoxelRCNNConvUpsampleHead"
    POOLER_RESOLUTION: 12
    POOLER_SAMPLING_RATIO: 2
    NUM_CONV: 4
    NUM_DEPTH: 24
    CLS_AGNOSTIC_VOXEL: True
    LOSS_WEIGHT: 3.0
    CUBIFY_THRESH: 0.2
  ROI_MESH_HEAD:
    NAME: "MeshRCNNGraphConvHead"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    NUM_STAGES: 3
    NUM_GRAPH_CONVS: 3
    GRAPH_CONV_DIM: 128
    GRAPH_CONV_INIT: "normal"
    GT_COORD_THRESH: 5.0
    CHAMFER_LOSS_WEIGHT: 1.0
    NORMALS_LOSS_WEIGHT: 0.1
    EDGE_LOSS_WEIGHT: 1.0
DATASETS:
  TRAIN: ("skull/train",)
  TEST: ("skull/test",)
SOLVER:
  #BASE_LR: 0.0001
 # BASE_LR: 0.00001
  BASE_LR: 0.00001
  WEIGHT_DECAY:  0.0002
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.1
  IMS_PER_BATCH: 2
  STEPS: (2000, 2500)
  MAX_ITER: 3250
  
#INPUT:
 #MAX_SIZE_TEST: 1027
 #MAX_SIZE_TRAIN: 1027
 #MIN_SIZE_TEST: 616
 #MIN_SIZE_TRAIN: (616,)
 
 
# ORIGINAL SOLVER:
#   BASE_LR: 0.02
#   WEIGHT_DECAY: 0.0001
#   STEPS: (8000, 10000)
#   MAX_ITER: 11000
#   WARMUP_ITERS: 1000
#   WARMUP_FACTOR: 0.1
